# Generated by Django 5.1 on 2026-04-22 21:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.FloatField()),
                ('url', models.URLField()),
                ('seller_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used')], max_length=20, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_kmeans', models.IntegerField(null=True)),
                ('cluster_dbscan', models.IntegerField(null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('deal_score', models.FloatField(null=True)),
                ('pca_x', models.FloatField(null=True)),
                ('pca_y', models.FloatField(null=True)),
                ('raw_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='search.rawprice')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('platforms', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawprice',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_prices', to='search.search'),
        ),
        migrations.CreateModel(
            name='AssociationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.JSONField()),
                ('consequent', models.JSONField()),
                ('support', models.FloatField()),
                ('confidence', models.FloatField()),
                ('lift', models.FloatField()),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_rules', to='search.search')),
            ],
        ),
        migrations.CreateModel(
            name='SearchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('best_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_deal_for_search_analyses', to='search.rawprice')),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_analyses', to='search.search')),
            ],
        ),
        migrations.AddIndex(
            model_name='search',
            index=models.Index(fields=['user', '-created_at'], name='search_sear_user_id_82110e_idx'),
        ),
        migrations.AddIndex(
            model_name='rawprice',
            index=models.Index(fields=['search'], name='search_rawp_search__1b5024_idx'),
        ),
        migrations.AddIndex(
            model_name='rawprice',
            index=models.Index(fields=['platform'], name='search_rawp_platfor_ae0c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawprice',
            unique_together={('search', 'url')},
        ),
        migrations.AddIndex(
            model_name='associationrule',
            index=models.Index(fields=['search'], name='search_asso_search__ab966e_idx'),
        ),
    ]
